/* eslint-disable prettier/prettier */

/** Notification `type` catalog — keep the app-side switch/icon-mapping in sync with these. */
export const NOTIFICATION_TYPES = {
  ORDER_PLACED: 'order_placed',
  ORDER_SHIPPED: 'order_shipped',
  ORDER_DELIVERED: 'order_delivered',
  ORDER_CANCELLED: 'order_cancelled',
  PAYMENT_SUCCESS: 'payment_success',
  PAYMENT_FAILED: 'payment_failed',
  NEW_MESSAGE: 'new_message',
  LOYALTY_POINTS_EARNED: 'loyalty_points_earned',
  LOYALTY_TIER_UPGRADE: 'loyalty_tier_upgrade',
  NEW_FOLLOWER: 'new_follower',
  LOW_STOCK: 'low_stock',
  SUBSCRIPTION_RENEWAL_REMINDER: 'subscription_renewal_reminder',
  SUBSCRIPTION_PAYMENT_FAILED: 'subscription_payment_failed',
  SUBSCRIPTION_CANCELLED: 'subscription_cancelled',
  PLATFORM_PLAN_RENEWAL_REMINDER: 'platform_plan_renewal_reminder',
  PLATFORM_PLAN_PAYMENT_FAILED: 'platform_plan_payment_failed',
  PROMOTION_REQUEST_SUBMITTED: 'promotion_request_submitted',
  PROMOTION_APPROVED: 'promotion_approved',
  PROMOTION_REJECTED: 'promotion_rejected',
  PROMOTION_PAYMENT_SUCCEEDED: 'promotion_payment_succeeded',
  PROMOTION_PAYMENT_FAILED: 'promotion_payment_failed',
  PROMOTION_GOING_LIVE: 'promotion_going_live',
  PROMOTION_EXPIRING_SOON: 'promotion_expiring_soon',
  PROMOTION_EXPIRED: 'promotion_expired',
  MANUAL_PAYMENT_SUBMITTED: 'manual_payment_submitted',
  MANUAL_PAYMENT_APPROVED: 'manual_payment_approved',
  MANUAL_PAYMENT_REJECTED: 'manual_payment_rejected',
  PAYOUT_AUTO_INITIATED: 'payout_auto_initiated',
  PAYOUT_COMPLETED: 'payout_completed',
  PAYOUT_REJECTED: 'payout_rejected',
  PAYOUT_RETRIED: 'payout_retried',
  STORE_APPROVED: 'store_approved',
  STORE_REJECTED: 'store_rejected',
  VERIFICATION_UNDER_REVIEW: 'verification_under_review',
  PLATFORM_CAMPAIGN_LIVE: 'platform_campaign_live',
  LISTING_APPROVED: 'listing_approved',
  LISTING_REJECTED: 'listing_rejected',
  PRODUCT_QUESTION: 'product_question',
  QUESTION_ANSWERED: 'question_answered',
  QUOTE_REQUESTED: 'quote_requested',
  QUOTE_SENT: 'quote_sent',
  QUOTE_ACCEPTED: 'quote_accepted',
  QUOTE_DECLINED: 'quote_declined',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

/** Maps a notification type to the NotificationPreference bucket that gates it. */
export const NOTIFICATION_CATEGORY: Record<string, 'orders' | 'messages' | 'promotions' | 'loyalty' | 'subscriptions' | 'finance'> = {
  [NOTIFICATION_TYPES.ORDER_PLACED]: 'orders',
  [NOTIFICATION_TYPES.ORDER_SHIPPED]: 'orders',
  [NOTIFICATION_TYPES.ORDER_DELIVERED]: 'orders',
  [NOTIFICATION_TYPES.ORDER_CANCELLED]: 'orders',
  [NOTIFICATION_TYPES.PAYMENT_SUCCESS]: 'orders',
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: 'orders',
  [NOTIFICATION_TYPES.NEW_MESSAGE]: 'messages',
  [NOTIFICATION_TYPES.LOYALTY_POINTS_EARNED]: 'loyalty',
  [NOTIFICATION_TYPES.LOYALTY_TIER_UPGRADE]: 'loyalty',
  [NOTIFICATION_TYPES.NEW_FOLLOWER]: 'promotions',
  [NOTIFICATION_TYPES.LOW_STOCK]: 'orders',
  [NOTIFICATION_TYPES.SUBSCRIPTION_RENEWAL_REMINDER]: 'subscriptions',
  [NOTIFICATION_TYPES.SUBSCRIPTION_PAYMENT_FAILED]: 'subscriptions',
  [NOTIFICATION_TYPES.SUBSCRIPTION_CANCELLED]: 'subscriptions',
  [NOTIFICATION_TYPES.PLATFORM_PLAN_RENEWAL_REMINDER]: 'subscriptions',
  [NOTIFICATION_TYPES.PLATFORM_PLAN_PAYMENT_FAILED]: 'subscriptions',
  [NOTIFICATION_TYPES.PROMOTION_REQUEST_SUBMITTED]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_APPROVED]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_REJECTED]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_PAYMENT_SUCCEEDED]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_PAYMENT_FAILED]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_GOING_LIVE]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_EXPIRING_SOON]: 'promotions',
  [NOTIFICATION_TYPES.PROMOTION_EXPIRED]: 'promotions',
  [NOTIFICATION_TYPES.MANUAL_PAYMENT_SUBMITTED]: 'orders',
  [NOTIFICATION_TYPES.MANUAL_PAYMENT_APPROVED]: 'orders',
  [NOTIFICATION_TYPES.MANUAL_PAYMENT_REJECTED]: 'orders',
  [NOTIFICATION_TYPES.PAYOUT_AUTO_INITIATED]: 'finance',
  [NOTIFICATION_TYPES.PAYOUT_COMPLETED]: 'finance',
  [NOTIFICATION_TYPES.PAYOUT_REJECTED]: 'finance',
  [NOTIFICATION_TYPES.PAYOUT_RETRIED]: 'finance',
  [NOTIFICATION_TYPES.STORE_APPROVED]: 'promotions',
  [NOTIFICATION_TYPES.STORE_REJECTED]: 'promotions',
  [NOTIFICATION_TYPES.VERIFICATION_UNDER_REVIEW]: 'promotions',
  [NOTIFICATION_TYPES.PLATFORM_CAMPAIGN_LIVE]: 'promotions',
  [NOTIFICATION_TYPES.LISTING_APPROVED]: 'promotions',
  [NOTIFICATION_TYPES.LISTING_REJECTED]: 'promotions',
  [NOTIFICATION_TYPES.PRODUCT_QUESTION]: 'messages',
  [NOTIFICATION_TYPES.QUESTION_ANSWERED]: 'messages',
  [NOTIFICATION_TYPES.QUOTE_REQUESTED]: 'orders',
  [NOTIFICATION_TYPES.QUOTE_SENT]: 'orders',
  [NOTIFICATION_TYPES.QUOTE_ACCEPTED]: 'orders',
  [NOTIFICATION_TYPES.QUOTE_DECLINED]: 'orders',
};
